# Generated by Django 3.2.9 on 2021-12-13 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('short_discription', models.CharField(blank=True, max_length=25, null=True, verbose_name=' короткое описание')),
                ('discription', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('price_with_discount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена со скидкой')),
                ('img', models.ImageField(blank=True, upload_to='products_images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.productcategory', verbose_name='категория продукта')),
            ],
        ),
    ]
