# Generated by Django 3.2.9 on 2021-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='its_new',
            field=models.BooleanField(default=False, verbose_name='это новый продукт'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='img',
            field=models.ImageField(blank=True, upload_to='category_images'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='its_popular',
            field=models.BooleanField(default=False, verbose_name='популярная категория'),
        ),
    ]
