# Generated by Django 3.2.9 on 2021-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211213_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='its_popular',
        ),
        migrations.AddField(
            model_name='product',
            name='its_popular',
            field=models.BooleanField(default=False, verbose_name='популярная категория'),
        ),
    ]
