# Generated by Django 3.2.9 on 2021-12-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211215_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='its_popular',
            field=models.BooleanField(default=False, verbose_name='популярные товары'),
        ),
    ]
