# Generated by Django 3.2.9 on 2021-12-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_its_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='its_new',
            new_name='is_new',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='its_popular',
            new_name='is_popular',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='short_discription',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='discription',
            new_name='description',
        ),
    ]
