# Generated by Django 3.2.9 on 2021-12-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211215_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, verbose_name='номер телефона'),
        ),
    ]
